ModelConfig:
    BASE_MODEL: "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species"
    # SEQUENCE_LENGTH: 150 # TODO prob dont need since embedding aggregation takes padding into account

TrainingDataConfig:
    TRAIN_DATA: "/scratch/Shares/layer/projects/sequence_similarity_search/training_data/grch38-gg-silva.txt"
    VAL_DATA: "/scratch/Shares/layer/projects/sequence_similarity_search/training_data/mpox-subsampled.txt"

TrainerConfig:
    DEVICES: 4
    EPOCHS: 100
    BATCH_SIZE: 256
    NUM_WORKERS: 32
    LEARNING_RATE: 1.0e-4
    WEIGHT_DECAY: 0.1

LoggingConfig:
    NAME: "nt-ia3"
    PROJECT: "seq-similarity"
    PROGRESS_BAR: False
    CHECKPOINT_DIR: "CHECKPOINTS-IA3"
