ModelConfig:
    BASE_MODEL: "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species"
    # SEQUENCE_LENGTH: 150 # TODO prob dont need since embedding aggregation takes padding into account

TrainingDataConfig:
    TRAIN_DATA: "/scratch/Shares/layer/projects/sequence_similarity_search/training_data/grch38-gg-silva.txt"
    VAL_DATA: "/scratch/Shares/layer/projects/sequence_similarity_search/training_data/mpox-subsampled.txt"

TrainerConfig:
    DEVICES: 4
    EPOCHS: 100
    BATCH_SIZE: 256
    ACCUMULATE_GRAD_BATCHES: 4
    NUM_WORKERS: 32
    LEARNING_RATE: 1.0e-3
    WEIGHT_DECAY: 0.01
    SIMILARITY_THRESHOLD: 0.8

LoggingConfig:
    NAME: "nt-ia3"
    PROJECT: "seq-similarity"
    PROGRESS_BAR: False
    CHECKPOINT_DIR: "CHECKPOINTS-IA3"

InferenceConfig:
    BASE_MODEL: "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species"
    ADAPTER_CHECKPOINT: "/Users/much8161/Repositories/ssearch/CHECKPOINTS-IA3/epoch=71-val_loss=0.0010/nucleotide-transformer-ia3-ssearch"
    OUTPUT_DIR: "/cache/much8161-results"
    BATCH_SIZE: 2048 # per gpu
    NUM_WORKERS_PER_GPU: 8
    NUM_GPUS: 4
    USE_AMP: True
    METAGENOMIC_INDEX_DATA:
        # - "/scratch/Shares/layer/projects/sequence_similarity_search/SRR12432009/BetaCoV_bat_Yunnan_RmYN02_2019_1.fq.gz"
        # - "/scratch/Shares/layer/projects/sequence_similarity_search/SRR12432009/BetaCoV_bat_Yunnan_RmYN02_2019_2.fq.gz"
        - "/cache/much8161-results/BetaCoV_bat_Yunnan_RmYN02_2019_1.fq.gz"
        - "/cache/much8161-results/BetaCoV_bat_Yunnan_RmYN02_2019_2.fq.gz"
    METAGENOMIC_QUERY_DATA:
        - "/scratch/Shares/layer/projects/sequence_similarity_search/viruses/BJ01.fasta"
        - "/scratch/Shares/layer/projects/sequence_similarity_search/viruses/WIV02.fasta"
        - "/scratch/Shares/layer/projects/sequence_similarity_search/viruses/WIV06.fasta"
        - "/scratch/Shares/layer/projects/sequence_similarity_search/viruses/ZC45.fasta"
        - "/scratch/Shares/layer/projects/sequence_similarity_search/viruses/RmYN02.fasta"
        - "/scratch/Shares/layer/projects/sequence_similarity_search/viruses/WIV05.fasta"
        - "/scratch/Shares/layer/projects/sequence_similarity_search/viruses/WIV1.fasta"
        - "/scratch/Shares/layer/projects/sequence_similarity_search/viruses/RaTG13.fasta" 
        - "/scratch/Shares/layer/projects/sequence_similarity_search/viruses/WIV04.fasta"
        - "/scratch/Shares/layer/projects/sequence_similarity_search/viruses/WIV07.fasta"



